import type {
  AccountFormState,
  PaymentFormState,
  PortalState,
  ResourceFormState,
  ResourceStatus,
  ResourceType,
  Course,
} from "./portal.types";

export const COURSES: Course[] = ["PCM", "IELTS", "French"];
export const CATEGORIES: ResourceType[] = ["Live Test", "Previous Test", "Revision Material", "Study Material"];
export const RESOURCE_STATUSES: ResourceStatus[] = ["Upcoming", "Live", "Archived"];

export const initialState: PortalState = {
  users: [
    {
      id: "admin-1",
      name: "Elevation Admin",
      email: "admin@elevation.test",
      role: "admin",
      accountStatus: "active",
      courses: ["PCM", "IELTS", "French"],
      joinedOn: "2026-07-01",
      phone: "+91 99999 88888",
      address: "Pune, Maharashtra",
    },
    {
      id: "teacher-1",
      name: "Priya Verma",
      email: "teacher@elevation.test",
      role: "teacher",
      accountStatus: "active",
      courses: ["PCM", "IELTS"],
      joinedOn: "2026-07-01",
      phone: "+91 98101 44556",
      address: "Delhi",
    },
    {
      id: "student-1",
      name: "Riya Sharma",
      email: "riya@elevation.test",
      role: "student",
      accountStatus: "active",
      courses: ["IELTS"],
      joinedOn: "2026-07-01",
      phone: "+91 98765 43210",
      guardianName: "Anita Sharma",
      address: "Pune, Maharashtra",
      performance: {
        averageScore: 78,
        attendance: 96,
        completion: 88,
        rank: 4,
        lastAssessment: "IELTS Mock 3",
      },
      scoreHistory: [
        { test: "IELTS Mock 1", score: 74, date: "2026-06-18" },
        { test: "IELTS Mock 2", score: 79, date: "2026-06-25" },
        { test: "IELTS Mock 3", score: 81, date: "2026-07-02" },
      ],
      payments: {
        total: 18000,
        paid: 12000,
        refunded: 0,
        due: 6000,
        nextDue: "2026-07-15",
        records: [
          { id: "pay-1", label: "Admission Fee", amount: 6000, date: "2026-05-12", method: "UPI", invoice: "INV-2026-000001", status: "Paid" },
          { id: "pay-2", label: "June Installment", amount: 6000, date: "2026-06-12", method: "Card", invoice: "INV-2026-000002", status: "Paid" },
          { id: "pay-3", label: "July Installment", amount: 6000, date: "2026-07-15", method: "UPI", invoice: "INV-2026-000003", status: "Pending" },
        ],
      },
    },
    {
      id: "student-2",
      name: "Arjun Mehta",
      email: "arjun@elevation.test",
      role: "student",
      accountStatus: "active",
      courses: ["PCM", "IELTS"],
      joinedOn: "2026-07-02",
      phone: "+91 98111 22334",
      guardianName: "Rajesh Mehta",
      address: "Delhi",
      performance: {
        averageScore: 84,
        attendance: 91,
        completion: 93,
        rank: 2,
        lastAssessment: "PCM Unit Test 5",
      },
      scoreHistory: [
        { test: "PCM Unit Test 3", score: 82, date: "2026-06-14" },
        { test: "PCM Unit Test 4", score: 85, date: "2026-06-24" },
        { test: "PCM Unit Test 5", score: 88, date: "2026-07-03" },
      ],
      payments: {
        total: 30500,
        paid: 23500,
        refunded: 0,
        due: 7000,
        nextDue: "2026-08-01",
        records: [
          { id: "pay-4", label: "Admission Fee", amount: 8000, date: "2026-05-10", method: "UPI", invoice: "INV-2026-000004", status: "Paid" },
          { id: "pay-5", label: "June Installment", amount: 7000, date: "2026-06-10", method: "Cash", invoice: "INV-2026-000005", status: "Paid" },
          { id: "pay-6", label: "July Installment", amount: 7000, date: "2026-07-01", method: "UPI", invoice: "INV-2026-000006", status: "Paid" },
          { id: "pay-7", label: "September Installment", amount: 8500, date: "2026-08-01", method: "Bank Transfer", invoice: "INV-2026-000007", status: "Pending" },
        ],
      },
    },
    {
      id: "student-3",
      name: "Sara Khan",
      email: "sara@elevation.test",
      role: "student",
      accountStatus: "active",
      courses: ["French"],
      joinedOn: "2026-07-04",
      phone: "+91 97222 44556",
      guardianName: "Nadeem Khan",
      address: "Bhopal",
      performance: {
        averageScore: 71,
        attendance: 89,
        completion: 76,
        rank: 8,
        lastAssessment: "French Grammar Check 2",
      },
      scoreHistory: [
        { test: "French Grammar Check 1", score: 68, date: "2026-06-20" },
        { test: "French Grammar Check 2", score: 72, date: "2026-07-01" },
        { test: "French Grammar Check 3", score: 74, date: "2026-07-08" },
      ],
      payments: {
        total: 15000,
        paid: 10000,
        refunded: 0,
        due: 5000,
        nextDue: "2026-08-05",
        records: [
          { id: "pay-8", label: "Admission Fee", amount: 5000, date: "2026-05-15", method: "UPI", invoice: "INV-2026-000008", status: "Paid" },
          { id: "pay-9", label: "June Installment", amount: 5000, date: "2026-06-15", method: "Card", invoice: "INV-2026-000009", status: "Paid" },
          { id: "pay-10", label: "July Installment", amount: 5000, date: "2026-07-15", method: "Bank Transfer", invoice: "INV-2026-000010", status: "Pending" },
        ],
      },
    },
  ],
  credentials: [
    {
      userId: "admin-1",
      password: "admin123",
      mustChangePassword: false,
      passwordUpdatedOn: "2026-07-01",
    },
    {
      userId: "teacher-1",
      password: "teacher123",
      mustChangePassword: false,
      passwordUpdatedOn: "2026-07-01",
    },
    {
      userId: "student-1",
      password: "student123",
      mustChangePassword: false,
      passwordUpdatedOn: "2026-07-01",
    },
    {
      userId: "student-2",
      password: "student123",
      mustChangePassword: false,
      passwordUpdatedOn: "2026-07-02",
    },
    {
      userId: "student-3",
      password: "student123",
      mustChangePassword: false,
      passwordUpdatedOn: "2026-07-04",
    },
  ],
  resources: [
    {
      id: "resource-1",
      title: "IELTS Reading Sample Test 1",
      course: "IELTS",
      category: "Live Test",
      status: "Upcoming",
      url: "https://forms.gle/vbc4L2bRRFuPqYdu9",
      answerReleaseStatus: "Hidden",
      description: "Sample reading test format shared through Google Forms.",
      addedOn: "2026-07-01",
    },
    {
      id: "resource-2",
      title: "IELTS Reading Previous Practice",
      course: "IELTS",
      category: "Previous Test",
      status: "Live",
      url: "https://forms.gle/vbc4L2bRRFuPqYdu9",
      answerUrl: "https://example.com/ielts-reading-answers",
      answerReleaseStatus: "Published",
      description: "Demo previous test entry for revision workflow.",
      addedOn: "2026-07-01",
    },
    {
      id: "resource-3",
      title: "PCM Diagnostic Format Preview",
      course: "PCM",
      category: "Revision Material",
      status: "Live",
      url: "https://example.com/pcm-sample",
      answerReleaseStatus: "Hidden",
      description: "Demo placeholder for a future PCM sample resource.",
      addedOn: "2026-07-01",
    },
    {
      id: "resource-4",
      title: "French Level Check Preview",
      course: "French",
      category: "Study Material",
      status: "Live",
      url: "https://example.com/french-sample",
      answerReleaseStatus: "Hidden",
      description: "Demo placeholder for a future French sample resource.",
      addedOn: "2026-07-01",
    },
  ],
  counters: {
    invoice: 11,
  },
};

export const emptyAccountForm: AccountFormState = {
  role: "student",
  name: "",
  email: "",
  courses: ["IELTS"],
  phone: "",
  guardianName: "",
  address: "",
  accountStatus: "active",
};

export const emptyPaymentForm: PaymentFormState = {
  studentId: "",
  label: "",
  amount: "",
  method: "UPI",
  date: new Date().toISOString().slice(0, 10),
  status: "Paid",
};

export const emptyResourceForm: ResourceFormState = {
  title: "",
  course: "IELTS",
  category: "Live Test",
  status: "Upcoming",
  url: "",
  answerUrl: "",
  answerReleaseStatus: "Hidden",
  description: "",
};
